name: WebdriverIO with Docker Compose

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  webdriverio_docker_compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Trigger jenkins job
      uses: jabbukka/jenkins-trigger@main
      with:
        url: "localhost"
        job_name: "pipeline_Automation"
        user_name: "sayrah"
        api_token: "114a11325efebca9c7aa7b19d384995e89"
        wait: "true"
        timeout: "1000"
